[username]
format = "[── $user]($style)@"
style_user = "bold blue"
style_root = "bold red"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold yellow"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo||"

[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style)"
disabled = false

# Replace the "❯" symbol in the prompt with "❯❯"
[character]
format = "❯❯ "
success_symbol = "❯❯(bold green) "
error_symbol = "❯❯(bold red) "

[golang]
symbol = "go||"

[java]
symbol = "java||"

[python]
symbol = "py||"

[nodejs]
symbol = "js||"
